<?php

// autoload_namespaces.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = $vendorDir;

return array(
    'SimplePie' => array($vendorDir . '/simplepie/simplepie/library'),
    'HTMLPurifier' => array($vendorDir . '/ezyang/htmlpurifier/library'),
);
